.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH runglass-doctor 1 2026-08-08 "runglass 0.3.3" "RunGlass Manual"
.SH NAME
runglass\-doctor \- Check local collector readiness and receipt storage
.SH SYNOPSIS
\fBrunglass doctor\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Check local collector readiness and receipt storage
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
