.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH runglass-github-comment 1 2026-05-15 "runglass 0.3.0" "RunGlass Manual"
.SH NAME
runglass\-github\-comment
.SH SYNOPSIS
\fBrunglass github comment\fR [\fB\-\-receipt\fR] [\fB\-\-repo\fR] [\fB\-\-pr\fR] [\fB\-\-auto\fR] [\fB\-\-dry\-run\fR] [\fB\-\-api\-url\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
.SH OPTIONS
.TP
\fB\-\-receipt\fR \fI<RECEIPT>\fR [default: latest]

.TP
\fB\-\-repo\fR \fI<REPO>\fR

.TP
\fB\-\-pr\fR \fI<PR>\fR

.TP
\fB\-\-auto\fR

.TP
\fB\-\-dry\-run\fR

.TP
\fB\-\-api\-url\fR \fI<API_URL>\fR

.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
