.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH runglass-export 1 2026-05-15 "runglass 0.3.0" "RunGlass Manual"
.SH NAME
runglass\-export
.SH SYNOPSIS
\fBrunglass export\fR [\fB\-\-html\fR] [\fB\-\-json\fR] [\fB\-\-markdown\fR] [\fB\-\-reverse\-patch\fR] [\fB\-\-bundle\fR] [\fB\-\-format\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fIRUN_ID\fR> 
.SH DESCRIPTION
.SH OPTIONS
.TP
\fB\-\-html\fR

.TP
\fB\-\-json\fR

.TP
\fB\-\-markdown\fR

.TP
\fB\-\-reverse\-patch\fR

.TP
\fB\-\-bundle\fR

.TP
\fB\-\-format\fR \fI<FORMATS>\fR

.br
\fIPossible values:\fR
.RS 14
.IP \(bu 2
html
.IP \(bu 2
json
.IP \(bu 2
markdown
.IP \(bu 2
reverse\-patch
.IP \(bu 2
bundle
.IP \(bu 2
summary\-md
.IP \(bu 2
ai
.RE
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIRUN_ID\fR>

