.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH runglass-github-detect 1 2026-08-08 "runglass 0.3.3" "RunGlass Manual"
.SH NAME
runglass\-github\-detect
.SH SYNOPSIS
\fBrunglass github detect\fR [\fB\-\-repo\fR] [\fB\-\-pr\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
.SH OPTIONS
.TP
\fB\-\-repo\fR \fI<REPO>\fR

.TP
\fB\-\-pr\fR \fI<PR>\fR

.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
