.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH runglass-snapshot 1 2026-05-15 "runglass 0.3.0" "RunGlass Manual"
.SH NAME
runglass\-snapshot
.SH SYNOPSIS
\fBrunglass snapshot\fR [\fB\-\-dry\-run\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
.SH OPTIONS
.TP
\fB\-\-dry\-run\fR

.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
