.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH runglass-prune 1 2026-08-08 "runglass 0.3.2" "RunGlass Manual"
.SH NAME
runglass\-prune
.SH SYNOPSIS
\fBrunglass prune\fR [\fB\-\-keep\fR] [\fB\-\-dry\-run\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
.SH OPTIONS
.TP
\fB\-\-keep\fR \fI<KEEP>\fR [default: 50]

.TP
\fB\-\-dry\-run\fR

.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
