.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH runglass-revert 1 2026-05-28 "runglass 0.3.1" "RunGlass Manual"
.SH NAME
runglass\-revert
.SH SYNOPSIS
\fBrunglass revert\fR [\fB\-\-file\fR] [\fB\-\-apply\fR] [\fB\-\-preview\fR] [\fB\-\-force\fR] [\fB\-\-skip\-changed\fR] [\fB\-\-dry\-run\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fIRUN_ID\fR> 
.SH DESCRIPTION
.SH OPTIONS
.TP
\fB\-\-file\fR \fI<FILES>\fR

.TP
\fB\-\-apply\fR
Apply the supported file revert after previewing it
.TP
\fB\-\-preview\fR
Preview the supported file revert without changing files
.TP
\fB\-\-force\fR

.TP
\fB\-\-skip\-changed\fR

.TP
\fB\-\-dry\-run\fR
Alias for \-\-preview
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIRUN_ID\fR>

