.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH runglass-open 1 2026-05-15 "runglass 0.3.0" "RunGlass Manual"
.SH NAME
runglass\-open \- Open a receipt in the local browser UI
.SH SYNOPSIS
\fBrunglass open\fR [\fB\-\-port\fR] [\fB\-h\fR|\fB\-\-help\fR] [\fIRUN_ID\fR] 
.SH DESCRIPTION
Open a receipt in the local browser UI
.SH OPTIONS
.TP
\fB\-\-port\fR \fI<PORT>\fR [default: 0]
Port to bind, or 0 for any free port
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
[\fIRUN_ID\fR] [default: latest]

